---
- hosts: elastic_cluster
  gather_facts: true
  roles:
      - elasticsearch
  become: true

- hosts: rabbit_cluster
  gather_facts: true
  roles:
      - rabbitmq
  become: true


- hosts: db
  gather_facts: true
  pre_tasks:
      - name: Gather Morpheus facts
        setup:
        delegate_to: "{{ item }}"
        delegate_facts: true
        with_items: "{{ groups['morpheus'] }}"
  roles:
      - percona
  become: true

- hosts: morpheus
  gather_facts: true
  roles:
      - morpheus
  become: true
