---
- hosts: elastic_cluster
  gather_facts: true
  roles:
      - elasticsearch
  become: true

- hosts: rabbit_cluster
  gather_facts: true
  roles:
      - rabbitmq
  become: true

- hosts: db
  gather_facts: true
  roles:
      - percona
  become: true

- hosts: morpheus
  gather_facts: true
  vars_files:
      - group_vars/rabbit_cluster
      - group_vars/elasticsearch
      - group_vars/db
      - group_vars/morpheus
  roles:
      - morpheus
  become: true
