---
- name: Add IP address of all hosts to all hosts
  blockinfile:
      dest: /etc/hosts
      block: | 
          {% for minion in groups['morpheus_3node_cluster'] %}
          {{ hostvars[minion]['ansible_all_ipv4_addresses'][0] }} {{ hostvars[minion]['ansible_hostname'] }}
          {% endfor %}

      marker: "# {mark} ANSIBLE MANAGED BLOCK"